name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
api-version: 1.14
version: 1.14 5
commands:
  knokkocore:
    description: Test command for the Knokko Core Plugin... dont use this unless I ask you to
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]