name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
version: 1.14 4
commands:
  knokkocore:
    description: Test command for the Knokko Core Plugin... dont use this unless I ask you to
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]